server:
  port: 9013

kafka:
  bootstrap-servers: localhost:9092
  topic.request-topic: requesttracktopic
  consumergroup: trackconsumergroup

cassandra:
  contactpoints: 127.0.0.1
  port: 9042
  keyspace: myKeyspace
  basepackages: com.trackService.config
spring:
  data:
    cassandra:
      keyspace-name: practice
      port: 9042
      password : cassandra
